table( X2023_STB_survey$Gender)
ECN <- table(X2023_STB_survey $Gender)
prop.table(ECN)
table(X2023_STB_survey $Gender, X2023_STB_survey $Grade)
barplot(table(X2023_STB_survey $Nationality))
barplot(table(X2023_STB_survey $`residential area`))
barplot(table(X2023_STB_survey $Gender,X2023_STB_survey $Grade))
pie(table(X2023_STB_survey $Grade))
barplot(table(X2023_STB_survey $Age))
entry <- table(X2023_STB_survey $Grade, X2023_STB_survey $Age)
barplot(entry, legend = TRUE)
boxplot(X2023_STB_survey$`Grade`, X2023_STB_survey$`Age`, main="업종별2020년1월미세먼지발생현황", col="yellow", names = c("야식업","중식"))
plot(x=X2023_STB_survey$`Grade`, y=X2023_STB_survey$`Age`, xlab="미세먼지", ylab="초미세먼지", main="미세먼지와초미세먼지의변화")
